metrics-server:
  args:
    - --kubelet-insecure-tls
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"