# helm/charts/monitoring/values.yaml
grafana:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    ports:
      - port: 80
        targetPort: 3000
        protocol: TCP
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: gp2
    volumeBindingMode: WaitForFirstConsumer
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki:3100
          access: proxy
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

prometheus:
  server:
    persistentVolume:
      enabled: true
      size: 10Gi
      storageClassName: gp2
      accessModes:
        - ReadWriteOnce
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      ports:
        - port: 80
          targetPort: 9090
          protocol: TCP
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    enableServiceLinks: true
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod

loki:
  enabled: true
  singleBinary:
    enabled: true
    replicas: 1
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp2
    accessModes:
      - ReadWriteOnce
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
  
  containerSecurityContext:
    runAsUser: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  structuredConfig:
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info
    
    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            period: 24h
            prefix: index_
    
    limits_config:
      retention_period: 168h
      max_query_length: 721h
      max_query_parallelism: 32

promtail:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  config:
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
        batchsize: 102400
        batchwait: 1s
        timeout: 10s
    
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_label_app_kubernetes_io_name']
            target_label: app
          - source_labels: ['__meta_kubernetes_pod_node_name']
            target_label: node_name
          - source_labels: ['__meta_kubernetes_namespace']
            target_label: namespace