# helm/charts/monitoring/values.yaml
grafana:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    ports:
      - port: 80
        targetPort: 3000
        protocol: TCP
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

prometheus:
  alertmanager:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: gp2
  server:
    retention: 15d
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClassName: gp2
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi

loki:
  enabled: true
  singleBinary:
    enabled: true
    replicas: 1
  auth_enabled: false
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  persistence:
    enabled: true
    size: 50Gi
    storageClass: gp2
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

promtail:
  enabled: true
  config:
    snippets:
      extraRelabelConfigs:
        - action: replace
          source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node_name
        - action: replace
          source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - action: replace
          source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - action: replace
          source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
    lokiAddress: http://monitoring-loki:3100/loki/api/v1/push
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi