# values.yaml
grafana:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    ports:
      - port: 80
        targetPort: 3000
        protocol: TCP
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: gp2
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki:3100
          access: proxy

prometheus:
  server:
    persistentVolume:
      enabled: true
      size: 10Gi
      storageClassName: gp2
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

loki:
  enabled: true
  loki:
    auth_enabled: false
    storage:
      type: filesystem
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: gp2
    serviceMonitor:
      enabled: true
    structuredConfig:
      common:
        path_prefix: /var/loki
        replication_factor: 1
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules

promtail:
  enabled: true
  config:
    clients:
      - url: http://monitoring-loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - docker: {}