falco:
  enabled: true
  driver:
    kind: modern-bpf
    enabled: true
  tty: true

  # --- Security Context ---
  containerSecurityContext:
    privileged: true  # Changed to true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: true  # Changed to true
    capabilities:
      add: ["SYS_PTRACE", "SYS_ADMIN", "SYS_RESOURCE"]
      drop: ["ALL"]

  # --- Resource Limits ---
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

  # --- Rules Configuration ---
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml
  
  # --- Output Configuration ---
  json_output: true
  stdout_output:
    enabled: true  # For Promtail to collect
  http_output:
    enabled: true
    url: "http://falco-falcosidekick:2801"

  # --- Metrics (Falco internal) ---
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false  # Use Falcosidekick metrics instead

  # --- Falcosidekick Integration ---
  falcosidekick:
    enabled: true
    # --- Falcosidekick Security Context ---
    containerSecurityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    # --- Resources ---
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    # --- Outputs ---
    config:
      debug: true
      customfields: "project:terraform-project,env:main"
      prometheus:
        enabled: true
        metricslabels:
          - "rule"
          - "priority"
      loki:
        host: "monitoring-loki:3100"
        labels:
          app: "falco"
          severity: "priority"
      webui:
        enabled: true
        url: "http://falco-falcosidekick-ui:2802"
    # --- Collectors (Metrics) ---
    metrics:
      enabled: true
      port: 2801
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: "monitoring-prometheus"  # Match your Prometheus instance

  # --- Pod Security ---
  podSecurityContext:
    runAsNonRoot: false  # Changed to false
    runAsUser: 0  # Changed to 0