nameOverride: monitoring
fullnameOverride: monitoring

prometheus:
  server:
    persistentVolume:
      enabled: true
      size: 4Gi
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - prometheus
              topologyKey: "kubernetes.io/hostname"

grafana:
  persistence:
    type: pvc
    enabled: true
    size: 2Gi

  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - grafana
            topologyKey: "kubernetes.io/hostname"

  datasources:
    datasources.yaml:
      apiVersion: 1
      deleteDatasources: []
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          access: proxy
          url: http://monitoring-loki:3100
          jsonData:
            maxLines: 1000
            timeout: 30
          version: 1
          editable: true

  adminUser: admin
  adminPassword: admin

loki:
  enabled: true
  singleBinary:
    replicas: 1
    
  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp2
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  monitoring:
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

  test:
    enabled: false

  loki:
    auth_enabled: false
    storage:
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      type: filesystem
    
    structuredConfig:
      analytics:
        reporting_enabled: false
      auth_enabled: false
      chunk_store_config:
        chunk_cache_config:
          enabled: false
        write_dedupe_cache_config:
          enabled: false
      common:
        compactor_address: ''
        path_prefix: /var/loki
        replication_factor: 1
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
      limits_config:
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
      memberlist:
        join_members:
          - monitoring-loki
      query_range:
        align_queries_with_step: true
        cache_results: true
        max_retries: 5
        results_cache:
          cache:
            enabled: false
      schema_config:
        configs:
          - from: "2020-10-24"
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h

promtail:
  enabled: true
  config:
    serverPort: 3101
    clients:
      - url: http://monitoring-loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
    positions:
      filename: /run/promtail/positions.yaml

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  tolerations:
    - operator: Exists

  serviceMonitor:
    enabled: false