grafana:
  persistence:
    enabled: true
    size: 2Gi
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  adminUser: admin
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki:3100
          access: proxy
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      falco-security:
        gnetId: 11914  # This is a popular Falco dashboard from Grafana's library
        revision: 1
        datasource: Prometheus
      falco-overview:
        json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "links": [],
            "panels": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "fieldConfig": {
                  "defaults": {
                    "custom": {
                      "drawStyle": "line",
                      "lineInterpolation": "linear",
                      "spanNulls": false
                    }
                  }
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "id": 1,
                "title": "Events Rate",
                "type": "timeseries",
                "targets": [
                  {
                    "expr": "rate(falco_events_total[5m])",
                    "legendFormat": "{{rule}}"
                  }
                ]
              },
              {
                "datasource": {
                  "type": "loki",
                  "uid": "loki"
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 12,
                  "y": 0
                },
                "id": 2,
                "options": {
                  "showLabels": true,
                  "showTime": true,
                  "sortOrder": "Descending",
                  "wrapLogMessage": false
                },
                "title": "Security Events",
                "type": "logs",
                "targets": [
                  {
                    "expr": "{job=\"falco\"} | json"
                  }
                ]
              },
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "fieldConfig": {
                  "defaults": {
                    "custom": {
                      "drawStyle": "line"
                    },
                    "unit": "s"
                  }
                },
                "gridPos": {
                  "h": 8,
                  "w": 12,
                  "x": 0,
                  "y": 8
                },
                "id": 3,
                "title": "Engine Uptime",
                "type": "timeseries",
                "targets": [
                  {
                    "expr": "falco_engine_uptime_seconds",
                    "legendFormat": "uptime"
                  }
                ]
              }
            ],
            "refresh": "10s",
            "schemaVersion": 38,
            "style": "dark",
            "time": {
              "from": "now-1h",
              "to": "now"
            },
            "title": "Falco Overview",
            "version": 1
          }