# helm/charts/api/values.yaml
replicaCount: 1

image:
  repository: ofurmaniuk/app-api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "api-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

vault:
  role: "api"
  secretPath: "secret/database"  
  template: |
    {{`{{- with secret "secret/database" -}}
    export DBHOST="{{ .Data.data.host }}"
    export DBUSER="{{ .Data.data.username }}"
    export DBPASS="{{ .Data.data.password }}"
    export DBPORT="{{ .Data.data.port }}"
    export DB="{{ .Data.data.dbname }}"
    {{- end }}`}}