replicaCount: 1

image:
  repository: ofurmaniuk/app-api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "api"

serviceAccount:
  create: true
  name: "api-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 30  
  periodSeconds: 20
  timeoutSeconds: 5  

readinessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 20  
  periodSeconds: 10
  timeoutSeconds: 5  
  failureThreshold: 3

database:
  host: "production-aurora-cluster.cluster-cdpxotwegnsy.us-east-2.rds.amazonaws.com"
  port: "5432"
  name: "mydatabase"
