replicaCount: 1

image:
  repository: ofurmaniuk/app-api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "api"

serviceAccount:
  create: true
  name: "api-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /api/status
  initialDelaySeconds: 30  # Increased from 15
  periodSeconds: 20
  timeoutSeconds: 5  # Increased from 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/status
  initialDelaySeconds: 20  # Increased from 5
  periodSeconds: 10
  timeoutSeconds: 5  # Increased from 1
  failureThreshold: 3


database:
  host: "production-aurora-cluster.cluster-cdpxotwegnsy.us-east-2.rds.amazonaws.com"
  port: "5432"
