replicaCount: 1

image:
  repository: ofurmaniuk/app-api
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: "api-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

database:
  host: "production-aurora-cluster.cluster-cdpxotwegnsy.us-east-2.rds.amazonaws.com"
  port: "5432"

vault:
  role: "api"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3