replicaCount: 1

image:
  repository: ofurmaniuk/app-api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "api"

serviceAccount:
  create: true
  name: "api-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /api/status
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

database:
  host: "production-aurora-cluster.cluster-cdpxotwegnsy.us-east-2.rds.amazonaws.com"
  port: "5432"
