replicaCount: 1

image:
  repository: ofurmaniuk/app-api
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: api-sa  # Match this with Vault configuration

vault:
  secretPath: "secret/data/database"  # Match your KV path
  role: "api"  # Match the role name in Vault

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi