apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: production
spec:
  template:
    spec:
      initContainers:
      - name: fix-path
        image: busybox:stable
        command: ['sh', '-c']
        args:
          - cp -r /usr/src/app/src/bin /usr/src/app/ && chmod +x /usr/src/app/bin/www
        volumeMounts:
          - name: app-files
            mountPath: /usr/src/app
      containers:
      - name: api
        volumeMounts:
          - name: app-files
            mountPath: /usr/src/app
      volumes:
        - name: app-files
          emptyDir: {}