apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: production
spec:
  selector:
    matchLabels:    # This was missing
      app: api
  template:
    metadata:
      labels:       # This was missing
        app: api    
    spec:
      containers:
        - name: api
          image: ofurmaniuk/app-api:latest  # This was missing/wrong
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config