apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: production
spec:
  replicas: 1
  selector:           # Add this
    matchLabels:
      app: web
  template:
    metadata:
      labels:        # Add this 
        app: web
    spec:
      containers:
        - name: web
          image: ofurmaniuk/app-web:latest  # Ensure image exists in your registry
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: web-config