vault:
  global:
    enabled: true
    tlsDisable: true   # Keeping it simple for pet project

  injector:
    enabled: true      # Required for API sidecar injection
    replicas: 1
    resources:
      requests:
        cpu: 100m      
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  server:
    dataStorage:
      enabled: true
      size: 1Gi
      storageClass: "gp2"
      accessMode: ReadWriteOnce

    standalone:
      enabled: true
      config: |
        ui = true
        
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "file" {
          path = "/vault/data"
        }

        # Important for API auth
        auth {
          kubernetes {
            role = "api"
            disable_local_ca_jwt = false
          }
        }

        audit {
          enabled = true
          type    = "file"
          options = {
            file_path = "/vault/logs/audit.log"
          }
        }

    service:
      enabled: true
      type: ClusterIP
      port: 8200

    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi

    extraEnvironmentVars:
      VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
      VAULT_LOG_LEVEL: "info"
      VAULT_K8S_AUTH_PATH: "kubernetes"  # Important for API auth

  ui:
    enabled: true
    serviceType: ClusterIP