# values.yaml for web chart
replicaCount: 1

image:
  repository: ofurmaniuk/app-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000  # Changed from 4000

# Update API host to match the actual service name
api:
  host: "http://api-svc"
  port: "80"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /
  initialDelaySeconds: 60  # Increased to give more startup time
  periodSeconds: 20

readinessProbe:
  path: /
  initialDelaySeconds: 30  # Increased to give more startup time
  periodSeconds: 10

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix