apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-database: "secret/database"
        vault.hashicorp.com/agent-inject-template-database: |
          {{`{{- with secret "secret/database" -}}
          export DBHOST="{{ .Data.data.host }}"
          export DBUSER="{{ .Data.data.username }}"
          export DBPASS="{{ .Data.data.password }}"
          export DBPORT="{{ .Data.data.port }}"
          export DB="{{ .Data.data.name }}"
          {{- end }}`}}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        vault.hashicorp.com/preserve-secret-case: "true"
    spec:
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              while [ ! -f /vault/secrets/database ]; do
                echo "Waiting for Vault secrets..."
                sleep 2
              done
              source /vault/secrets/database
              exec npm start
          env:
            - name: PORT
              value: "3000"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vault-secrets
              mountPath: /vault/secrets
              readOnly: true
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory
