apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api"
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/database"
        vault.hashicorp.com/agent-inject-template-database: |
          #!/bin/sh
          {{ "{{" }}- with secret "secret/data/database" {{ "}}" }}
          export DBUSER="{{ "{{" }} .Data.data.username {{ "}}" }}"
          export DBPASS="{{ "{{" }} .Data.data.password {{ "}}" }}"
          export DB="{{ "{{" }} .Data.data.dbname {{ "}}" }}"
          {{ "{{" }}- end {{ "}}" }}
    spec:
      serviceAccountName: api-sa
      containers:
        - name: api
          image: ofurmaniuk/app-api:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              set -e
              . /vault/secrets/database
              echo "Database credentials loaded"
              export DBHOST="production-aurora-cluster.cluster-cdpxotwegnsy.us-east-2.rds.amazonaws.com"
              export DBPORT="5432"
              echo "Starting API server..."
              exec node ./src/bin/www
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config
          readinessProbe:
            httpGet:
              path: /api/status
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/status
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"