apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api"
        vault.hashicorp.com/agent-inject-secret-database: "secret/database"
        vault.hashicorp.com/agent-inject-template-database: |
          export DBUSER="{{ "{{" }} .Data.data.username {{ "}}" }}"
          export DBPASS="{{ "{{" }} .Data.data.password {{ "}}" }}"
          export DB="{{ "{{" }} .Data.data.dbname {{ "}}" }}"
          export DBHOST="production-aurora-cluster.cluster-cdpxotwegnsy.us-east-2.rds.amazonaws.com"
          export DBPORT="5432"
    spec:
      serviceAccountName: api-sa
      containers:
        - name: api
          image: ofurmaniuk/app-api:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - -c
            - |
              set -x
              echo "Loading database credentials..."
              source /vault/secrets/database
              echo "Verifying environment variables..."
              env | grep DB
              if [ -z "$DBUSER" ] || [ -z "$DBPASS" ] || [ -z "$DB" ] || [ -z "$DBHOST" ]; then
                echo "Error: Database environment variables are not set correctly"
                echo "Required variables: DBUSER, DBPASS, DB, DBHOST"
                exit 1
              fi
              echo "Starting API server..."
              exec node ./src/bin/www
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/status
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5