apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}  # Simplified from include "api.fullname"
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api"
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/database"
        vault.hashicorp.com/addr: "http://vault.vault:8200"
            #!/bin/sh
            {{`{{- with secret "secret/data/database" }}
            export DBUSER="{{ .Data.data.username }}"
            export DBPASS="{{ .Data.data.password }}"
            export DB="{{ .Data.data.dbname }}"
            {{- end }}`}}
            export DBHOST="{{ .Values.database.host }}"
            export DBPORT="{{ .Values.database.port }}"
    spec:
      serviceAccountName: api-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              source /vault/secrets/database && \
              export DBHOST="{{ .Values.database.host }}" && \
              export DBPORT="{{ .Values.database.port }}" && \
              npm start
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: DBHOST
              value: "{{ .Values.database.host }}"
            - name: DBPORT
              value: "{{ .Values.database.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}