# helm/charts/api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api"
        vault.hashicorp.com/agent-inject-secret-db-creds: "secret/data/database"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{`{{- with secret "secret/data/database" -}}
          export DBHOST="{{ .Data.data.host }}"
          export DBUSER="{{ .Data.data.username }}"
          export DBPASS="{{ .Data.data.password }}"
          export DBPORT="{{ .Data.data.port }}"
          export DB="{{ .Data.data.dbname }}"
          {{- end }}`}}
    spec:
      serviceAccountName: {{ include "api.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              while [ ! -f /vault/secrets/db-creds ]; do
                echo "Waiting for Vault secrets..."
                sleep 2
              done
              source /vault/secrets/db-creds && npm start
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}