# ServiceAccount for your API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: production
---
# ClusterRoleBinding for Vault authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: api-sa
  namespace: production