apiVersion: v2
name: ingress-nginx
description: Ingress-Nginx Controller Helm Chart
type: application
version: 1.0.0
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx