name: API-Pipeline-Fresh

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "apps/api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: ./apps/api
        run: |
          npm install
          npm install --save-dev eslint@8.56.0 \
                               prettier \
                               eslint-config-prettier \
                               eslint-plugin-prettier

      - name: Run ESLint
        working-directory: ./apps/api
        run: ./node_modules/.bin/eslint . --max-warnings 999 || true  # Allow warnings for now

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: true
          tags: ofurmaniuk/app-api:latest,ofurmaniuk/app-api:${{ github.sha }}