name: Infrastructure-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "modules/**"
      - ".github/workflows/infra-cd.yaml"
      - "*.tf"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v3
      - run: tflint --init
      - name: Run TFLint with logging
        run: |
          tflint --format json > tflint-results.json
          tflint -f compact | tee tflint-output.txt
        continue-on-error: true

      - name: Upload TFLint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tflint-results
          path: |
            tflint-results.json
            tflint-output.txt

  preparation:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Terraform
        run: make ubuntu-install
      
      - name: Initialize Terraform
        run: make init
        
      - name: Terraform Plan
        run: |
          make plan | tee tf-plan-output.txt
          
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: tf-plan-output.txt

  deploy:
    needs: preparation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Terraform
        run: make ubuntu-install
      
      - name: Initialize Terraform
        run: make init
      
      - name: Apply Infrastructure
        run: make apply

  destroy:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Terraform
        run: make ubuntu-install
      
      - name: Initialize Terraform
        run: make init
      
      - name: Destroy Infrastructure
        run: make destroy