name: Infra-cd 

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
        default: 'plan'
  push:
    branches: [ "main" ]
    paths:
      - "modules/**"
      - ".github/workflows/infra-cd.yaml"
      - "*.tf"

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: us-east-2
  TF_IN_AUTOMATION: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.1"

      - uses: terraform-linters/setup-tflint@v3
      - run: tflint --init
      
      - name: Run TFLint and upload to S3
        run: |
          # Create timestamp for unique log files
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          
          # Run TFLint and save outputs
          tflint --format json | tee tflint-${TIMESTAMP}.json
          tflint -f compact | tee tflint-${TIMESTAMP}.log
          
          # Upload to same bucket as tfstate, different prefix
          aws s3 cp tflint-${TIMESTAMP}.json s3://ofurmaniuk/terraform-project/lint-logs/tflint-${TIMESTAMP}.json
          aws s3 cp tflint-${TIMESTAMP}.log s3://ofurmaniuk/terraform-project/lint-logs/tflint-${TIMESTAMP}.log
        continue-on-error: true

  preparation:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.1"
      
      - name: Initialize Terraform
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan | tee tf-plan-output.txt
        continue-on-error: true
          
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: tf-plan-output.txt

      - name: Check Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  deploy:
    if: github.event.inputs.action == 'apply'
    needs: preparation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.1"
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Apply Infrastructure
        id: apply
        run: terraform apply -auto-approve
      
      - name: Verify Infrastructure
        run: |
          # Check EKS cluster status
          aws eks describe-cluster --name production-cluster --query 'cluster.status' || exit 1
          
          # Check RDS status
          aws rds describe-db-clusters --query 'DBClusters[?DBClusterIdentifier==`production-aurora-cluster`].Status' || exit 1